### ISSUE TITLE
Bugs when unMounted subroutine is calling

### ISSUE THREAD

**Issue by li-xilin** [RealCoolSnow/vue3-audio-player#2]
Try calling the pause method in the unmounted function, but the data context for play or pause method has been destroyed at that time.

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'pause')
    at pause (webpack-internal:///./node_modules/vue3-audio-player/dist/index.es.js:772:25)
    at eval (webpack-internal:///./node_modules/vue3-audio-player/dist/index.es.js:881:7)
    at callWithErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:357:18)
    at callWithAsyncErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:367:17)
    at Array.hook.__weh.hook.__weh (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:3388:19)
    at flushPostFlushCbs (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:591:41)
    at flushJobs (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:643:5)
```

In file index.es.js, At line 596 
```
    onUnmounted(() => {
      if (toucher)
        toucher.destroy();
      pause(); // Exception
    });
    };
```

**Comment by RealCoolSnow** [comment]
thanks, it has fixed.
